### ISSUE TITLE
Build fails at targetlittlefs-do

### ISSUE THREAD

**Issue by coffandro** [InfiniTimeOrg/InfiniSim#121]
I run `cmake -S . -B build` which builds fine but when i run `cmake --build build -j4` i get the following output and errors

```
[  1%] Generating lv_font_sys_48.c
[  1%] Generating open_sans_light.c
[  1%] Generating fontawesome_weathericons.c
[  1%] Built target infinitime_fonts_lv_font_sys_48
[  1%] Built target infinitime_fonts_fontawesome_weathericons
[  1%] Generating jetbrains_mono_42.c
[  1%] Generating jetbrains_mono_76.c
[  1%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_core/lv_disp.c.o
[  1%] Built target infinitime_fonts_open_sans_light
[  2%] Generating jetbrains_mono_bold_20.c
[  2%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_core/lv_group.c.o
[  2%] Built target infinitime_fonts_jetbrains_mono_76
[  2%] Built target infinitime_fonts_jetbrains_mono_42
[  2%] Generating jetbrains_mono_extrabold_compressed.c
[  3%] Generating lv_font_navi_80.c
[  3%] Built target infinitime_fonts_jetbrains_mono_extrabold_compressed
[  4%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_core/lv_indev.c.o
[  4%] Built target infinitime_fonts_jetbrains_mono_bold_20
[  4%] Generate fonts and images for resource package
[  4%] Built target infinitime_fonts_lv_font_navi_80
[  5%] Building C object CMakeFiles/littlefs.dir/InfiniTime/src/libs/littlefs/lfs_util.c.o
[  5%] Building C object CMakeFiles/QCBOR.dir/InfiniTime/src/libs/QCBOR/src/ieee754.c.o
[  6%] Building C object CMakeFiles/QCBOR.dir/InfiniTime/src/libs/QCBOR/src/qcbor_decode.c.o
[  6%] Building C object CMakeFiles/littlefs.dir/InfiniTime/src/libs/littlefs/lfs.c.o
[  6%] Linking C static library liblittlefs.a
[  6%] Building C object CMakeFiles/QCBOR.dir/InfiniTime/src/libs/QCBOR/src/qcbor_encode.c.o
[  6%] Built target littlefs
[  6%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_core/lv_obj.c.o
[  6%] Generating sim_background.h
[  6%] Built target infinisim_img_background
[  7%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_core/lv_refr.c.o
[  7%] Building C object CMakeFiles/QCBOR.dir/InfiniTime/src/libs/QCBOR/src/qcbor_err_to_str.c.o
[  8%] Building C object CMakeFiles/QCBOR.dir/InfiniTime/src/libs/QCBOR/src/UsefulBuf.c.o
[  8%] Linking C static library libQCBOR.a
[  8%] Built target QCBOR
[  8%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_core/lv_style.c.o
[  8%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_draw_arc.c.o
[  8%] Building C object external/miniz/CMakeFiles/miniz.dir/miniz.c.o
/mnt/c/Users/Cornelius/InfiniSim/external/miniz/miniz.c:3089:9: note: ‘#pragma message: Using fopen, ftello, fseeko, stat() etc. path for file I/O - this path may not support large files.’
 3089 | #pragma message("Using fopen, ftello, fseeko, stat() etc. path for file I/O - this path may not support large files.")
      |         ^~~~~~~
[  9%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_draw_blend.c.o
[  9%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_draw_img.c.o
[ 10%] Linking C static library libminiz.a
[ 10%] Built target miniz
[ 10%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_draw_label.c.o
[ 11%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_draw_line.c.o
[ 11%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_draw_mask.c.o
[ 11%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_draw_rect.c.o
[ 12%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_draw_triangle.c.o
[ 12%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_img_buf.c.o
[ 13%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_img_cache.c.o
[ 13%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_draw/lv_img_decoder.c.o
[ 13%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font.c.o
[ 14%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_dejavu_16_persian_hebrew.c.o
[ 14%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_fmt_txt.c.o
[ 14%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_loader.c.o
[ 15%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_10.c.o
[ 15%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_12.c.o
[ 15%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_12_subpx.c.o
[ 15%] Building C object fonts/CMakeFiles/infinitime_fonts.dir/jetbrains_mono_42.c.o
[ 16%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_14.c.o
[ 16%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_16.c.o
[ 17%] Building C object fonts/CMakeFiles/infinitime_fonts.dir/jetbrains_mono_76.c.o
[ 18%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_18.c.o
[ 18%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_20.c.o
[ 18%] Building C object fonts/CMakeFiles/infinitime_fonts.dir/jetbrains_mono_bold_20.c.o
[ 18%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_22.c.o
[ 19%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_24.c.o
[ 20%] Building C object fonts/CMakeFiles/infinitime_fonts.dir/jetbrains_mono_extrabold_compressed.c.o
[ 20%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_26.c.o
[ 20%] Building C object fonts/CMakeFiles/infinitime_fonts.dir/lv_font_navi_80.c.o
[ 20%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_28.c.o
[ 21%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_28_compressed.c.o
[ 21%] Building C object fonts/CMakeFiles/infinitime_fonts.dir/lv_font_sys_48.c.o
[ 21%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_30.c.o
/mnt/c/Users/Cornelius/InfiniSim/node_modules/ts-node/src/transpilers/swc.ts:262
      throw new Error(
            ^
Error: @swc/core threw an error when attempting to validate swc compiler options.
You may be using an old version of swc which does not support the options used by ts-node.
Try upgrading to the latest version of swc.
Error message from swc:
Failed to deserialize buffer as swc::config::Options
JSON: {"sourceMaps":true,"module":{"noInterop":false,"type":"commonjs","strictMode":true,"ignoreDynamic":false},"swcrc":false,"jsc":{"parser":{"syntax":"typescript","tsx":false,"dynamicImport":true,"importAssertions":true},"target":"es5","transform":{"legacyDecorator":true,"react":{"throwIfNamespace":false,"useBuiltins":false,"runtime":"automatic"}},"keepClassNames":false,"experimental":{"keepImportAssertions":true}}}

Caused by:
    unknown field `keepImportAssertions`, expected one of `plugins`, `keepImportAttributes`, `emitAssertForImportAttributes`, `cacheRoot`, `disableBuiltinTransformsForInternalTesting` at line 1 column 415
    at createVariant (/mnt/c/Users/Cornelius/InfiniSim/node_modules/ts-node/src/transpilers/swc.ts:262:13)
    at createSwcOptions (/mnt/c/Users/Cornelius/InfiniSim/node_modules/ts-node/src/transpilers/swc.ts:211:25)
    at create (/mnt/c/Users/Cornelius/InfiniSim/node_modules/ts-node/src/transpilers/swc.ts:56:41)
    at createTranspiler (/mnt/c/Users/Cornelius/InfiniSim/node_modules/ts-node/src/index.ts:784:16)
    at createTranspileOnlyGetOutputFunction (/mnt/c/Users/Cornelius/InfiniSim/node_modules/ts-node/src/index.ts:1341:28)
    at createFromPreloadedConfig (/mnt/c/Users/Cornelius/InfiniSim/node_modules/ts-node/src/index.ts:1404:34)
    at phase4 (/mnt/c/Users/Cornelius/InfiniSim/node_modules/ts-node/src/bin.ts:543:44)
    at bootstrap (/mnt/c/Users/Cornelius/InfiniSim/node_modules/ts-node/src/bin.ts:95:10)
    at main (/mnt/c/Users/Cornelius/InfiniSim/node_modules/ts-node/src/bin.ts:55:10)
    at Object.<anonymous> (/mnt/c/Users/Cornelius/InfiniSim/node_modules/ts-node/src/bin.ts:800:3)
Traceback (most recent call last):
  File "/mnt/c/Users/Cornelius/InfiniSim/InfiniTime/src/resources/generate-img.py", line 56, in <module>
    main()
  File "/mnt/c/Users/Cornelius/InfiniSim/InfiniTime/src/resources/generate-img.py", line 51, in main
    subprocess.check_call(line)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/mnt/c/Users/Cornelius/InfiniSim/node_modules/.bin/lv_img_conv', '/mnt/c/Users/Cornelius/InfiniSim/InfiniTime/src/resources/images/pine_logo.png', '--force', '--output-file', 'pine_small.bin', '--color-format', 'CF_TRUE_COLOR_ALPHA', '--output-format', 'bin', '--binary-format', 'ARGB8565_RBSWAP']' returned non-zero exit status 1.
gmake[2]: *** [resources/CMakeFiles/GenerateResources.dir/build.make:73: resources/CMakeFiles/GenerateResources] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:567: resources/CMakeFiles/GenerateResources.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 21%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_32.c.o
[ 22%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_34.c.o
[ 23%] Building C object fonts/CMakeFiles/infinitime_fonts.dir/open_sans_light.c.o
[ 23%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_36.c.o
[ 24%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_38.c.o
[ 24%] Building C object fonts/CMakeFiles/infinitime_fonts.dir/fontawesome_weathericons.c.o
[ 24%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_40.c.o
[ 24%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_42.c.o
[ 25%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_44.c.o
[ 25%] Linking C static library libinfinitime_fonts.a
[ 25%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_46.c.o
[ 25%] Built target infinitime_fonts
[ 25%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_48.c.o
[ 26%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_montserrat_8.c.o
[ 26%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_simsun_16_cjk.c.o
[ 26%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_unscii_16.c.o
[ 27%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_font/lv_font_unscii_8.c.o
[ 27%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_gpu/lv_gpu_nxp_pxp.c.o
[ 28%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_gpu/lv_gpu_nxp_pxp_osa.c.o
[ 28%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_gpu/lv_gpu_nxp_vglite.c.o
[ 28%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_gpu/lv_gpu_stm32_dma2d.c.o
[ 29%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_hal/lv_hal_disp.c.o
[ 29%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_hal/lv_hal_indev.c.o
[ 29%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_hal/lv_hal_tick.c.o
[ 30%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_anim.c.o
[ 30%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_area.c.o
[ 30%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_async.c.o
[ 31%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_bidi.c.o
[ 31%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_color.c.o
[ 32%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_debug.c.o
[ 32%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_fs.c.o
[ 32%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_gc.c.o
[ 33%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_ll.c.o
[ 33%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_log.c.o
[ 33%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_math.c.o
[ 34%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_mem.c.o
[ 34%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_printf.c.o
[ 34%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_task.c.o
[ 35%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_templ.c.o
[ 35%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_txt.c.o
[ 36%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_txt_ap.c.o
[ 36%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_misc/lv_utils.c.o
[ 36%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_themes/lv_theme.c.o
[ 37%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_themes/lv_theme_empty.c.o
[ 37%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_themes/lv_theme_material.c.o
[ 37%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_themes/lv_theme_mono.c.o
[ 38%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_themes/lv_theme_template.c.o
[ 38%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_arc.c.o
[ 39%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_bar.c.o
[ 39%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_btn.c.o
[ 39%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_btnmatrix.c.o
[ 40%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_calendar.c.o
[ 40%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_canvas.c.o
[ 40%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_chart.c.o
[ 41%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_checkbox.c.o
[ 41%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_cont.c.o
[ 41%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_cpicker.c.o
[ 42%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_dropdown.c.o
[ 42%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_gauge.c.o
[ 43%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_img.c.o
[ 43%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_imgbtn.c.o
[ 43%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_keyboard.c.o
[ 44%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_label.c.o
[ 44%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_led.c.o
[ 44%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_line.c.o
[ 45%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_linemeter.c.o
[ 45%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_list.c.o
[ 45%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_msgbox.c.o
[ 46%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_objmask.c.o
[ 46%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_objx_templ.c.o
[ 47%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_page.c.o
[ 47%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_roller.c.o
[ 47%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_slider.c.o
[ 48%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_spinbox.c.o
[ 48%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_spinner.c.o
[ 48%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_switch.c.o
[ 49%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_table.c.o
[ 49%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_tabview.c.o
[ 49%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_textarea.c.o
[ 50%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_tileview.c.o
[ 50%] Building C object CMakeFiles/sim-base.dir/InfiniTime/src/libs/lvgl/src/lv_widgets/lv_win.c.o
[ 51%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/GC9A01.c.o
[ 51%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/ILI9341.c.o
[ 51%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/R61581.c.o
[ 52%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/SHARP_MIP.c.o
[ 52%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/SSD1963.c.o
[ 52%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/ST7565.c.o
[ 53%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/UC1610.c.o
[ 53%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/drm.c.o
[ 53%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/fbdev.c.o
[ 54%] Building C object CMakeFiles/sim-base.dir/lv_drivers/display/monitor.c.o
[ 54%] Building C object CMakeFiles/sim-base.dir/lv_drivers/gtkdrv/gtkdrv.c.o
[ 55%] Building C object CMakeFiles/sim-base.dir/lv_drivers/indev/AD_touch.c.o
[ 55%] Building C object CMakeFiles/sim-base.dir/lv_drivers/indev/FT5406EE8.c.o
[ 55%] Building C object CMakeFiles/sim-base.dir/lv_drivers/indev/XPT2046.c.o
[ 56%] Building C object CMakeFiles/sim-base.dir/lv_drivers/indev/evdev.c.o
[ 56%] Building C object CMakeFiles/sim-base.dir/lv_drivers/indev/keyboard.c.o
[ 56%] Building C object CMakeFiles/sim-base.dir/lv_drivers/indev/libinput.c.o
[ 57%] Building C object CMakeFiles/sim-base.dir/lv_drivers/indev/mouse.c.o
[ 57%] Building C object CMakeFiles/sim-base.dir/lv_drivers/indev/mousewheel.c.o
[ 57%] Building C object CMakeFiles/sim-base.dir/lv_drivers/win32drv/win32drv.c.o
[ 58%] Building C object CMakeFiles/sim-base.dir/lv_drivers/win_drv.c.o
[ 58%] Building CXX object CMakeFiles/sim-base.dir/sim/FreeRTOS.cpp.o
[ 59%] Building CXX object CMakeFiles/sim-base.dir/sim/task.cpp.o
[ 59%] Building CXX object CMakeFiles/sim-base.dir/sim/timers.cpp.o
[ 59%] Building CXX object CMakeFiles/sim-base.dir/sim/queue.cpp.o
[ 60%] Building CXX object CMakeFiles/sim-base.dir/sim/portmacro_cmsis.cpp.o
[ 60%] Building CXX object CMakeFiles/sim-base.dir/sim/libraries/delay/nrf_delay.cpp.o
[ 60%] Building CXX object CMakeFiles/sim-base.dir/sim/nrfx/hal/nrf_gpio.cpp.o
[ 61%] Building CXX object CMakeFiles/sim-base.dir/sim/nrfx/hal/nrf_rtc.cpp.o
[ 61%] Building CXX object CMakeFiles/sim-base.dir/sim/nrfx/mdk/nrf52.cpp.o
[ 62%] Linking CXX static library libsim-base.a
[ 62%] Built target sim-base
gmake: *** [Makefile:136: all] Error 2
```

**Comment by NeroBurner** [comment]
It's still en error with the `lv_img_conf` npm executable. Seems nothing concerning the `littlefs-do` executable. I think the build will succeed if you disable resource generation

```
Traceback (most recent call last):
  File "/mnt/c/Users/Cornelius/InfiniSim/InfiniTime/src/resources/generate-img.py", line 56, in <module>
    main()
  File "/mnt/c/Users/Cornelius/InfiniSim/InfiniTime/src/resources/generate-img.py", line 51, in main
    subprocess.check_call(line)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/mnt/c/Users/Cornelius/InfiniSim/node_modules/.bin/lv_img_conv', '/mnt/c/Users/Cornelius/InfiniSim/InfiniTime/src/resources/images/pine_logo.png', '--force', '--output-file', 'pine_small.bin', '--color-format', 'CF_TRUE_COLOR_ALPHA', '--output-format', 'bin', '--binary-format', 'ARGB8565_RBSWAP']' returned non-zero exit status 1.
```

Try to run the failing command (the one with `lv_img_conv`) directly in the shell.

**Comment by NeroBurner** [comment]
just merged https://github.com/InfiniTimeOrg/InfiniSim/pull/122 stating a minimum version of nodejs of 14.0 and issueing a warning if a lower version is deteted.

Although it seems 14.0 isn't quite the lowest version as our Ubuntu 22.04 base build fails as well

Maybe https://github.com/InfiniTimeOrg/InfiniSim/issues/120 helps you, as they've found that downgrading (or pinning) of the `@swc/core@1.3.80` package (anything below `1.3.83`)  resolves the issue

**Comment by coffandro** [comment]
That fixes it

**Comment by NeroBurner** [comment]
The swc thingy or the disable resources flag?

On September 18, 2023 8:56:00 AM GMT+02:00, Cornelius Andreas Rosenaa ***@***.***> wrote:
>That fixes it
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/InfiniTimeOrg/InfiniSim/issues/121#issuecomment-1722845458
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by coffandro** [comment]
Installing the `@swc/core@1.3.80` instead of newest version, i think it should be added to the install instructions

**Comment by FintasticMan** [comment]
We are working on a solution that likely won't require downgrading packages.

**Comment by NeroBurner** [comment]
Yes Feedback on https://github.com/InfiniTimeOrg/InfiniTime/pull/1863 would be highly appreciated

**Comment by boldandbusted** [comment]
Just FYI, this also fixed the same problem for me. Changed the install step to:

```
npm install ts-node@10.9.1 @swc/core@1.3.80 lv_img_conv@0.3.0
```

Cheers.
